import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import data from '../data/education.json'
import styles from '../styles/About.module.css'
import { useState } from 'react'
import Card from '../components/card/about'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function About() {
    const [information, setInformation] = useState([...data])
  
    return (
      <>
        <Head>
          <title>About Us</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <div class="navBar">
            <div class="navTitle">About Us</div>
              <div class="navButton">
                <Link className={styles.link} href="..">Back</Link>
              </div>
          </div>
          
          {
            information && information.map((info, index) => {
                return(
                    <Card 
                        class = "infoCard"
                        key={index}
                        studentNumber={info.studentNumber}                            
                        gpa={info.gpa}
                        graduated={info.graduted}
                        font="20px"
                    />
                )
            })
          }
        </main>
      </>
    )
  }
  